---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy website files
  copy:
    src: files/website/
    dest: /var/www/html/
  notify: Reload Nginx

