---
- name: Install Docker using geerlingguy.docker role
  hosts: all
  become: true  # Ensures tasks are run with sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Specify the Python interpreter
  roles:
    - geerlingguy.docker

  tasks:
    - name: Install Python pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Print Docker version
      shell: docker --version
      register: docker_version_output

    - name: Show Docker version
      debug:
        msg: "Docker Version: {{ docker_version_output.stdout }}"

    - name: Docker login
      docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"
        registry: "https://index.docker.io/v1/"
      register: docker_login_output

    - name: Run Docker image
      docker_container:
        name: mvc-app  # Name of the container
        image: "{{ DOCKER_USERNAME }}/mvc:latest"  # Replace with your Docker image
        state: started
      register: run_container_output

    - name: Show container output
      debug:
        msg: "Container Run Output: {{ run_container_output }}"
