instance_name = "my-dev-instance"
project_id = "ukg-righscale-migration"
region = "us-central1"
machine_type  = "e2-medium"
zone          = "us-central1-a"
image         = "ubuntu-2004-focal-v20240830"
network       = "default"
subnetwork    = "default"
network_tags  = ["test", "dev"]
username       = "devendra_srivastava"             # SSH username