name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: self-hosted

    # Use Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.PROVIDER }}      
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/mvc:latest

      - name: Test Image 
        run: |
            docker run -d ${{ secrets.DOCKER_USERNAME }}/mvc:latest
            sleep 5
            docker logs mvc-app | grep -q "Application started" || exit 1

      - name: Push Image to Repo
        uses: docker/build-push-action@v6
        with:
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/mvc:latest

            